### ISSUE TITLE
First Editor Prototype

### ISSUE THREAD

**Issue by Larbonard** [TINF16C-WE2-IE/TheIndoorExplorer#2]
Implement a basic prototype of the map editor as discussed on 2017/09/19 
See attached sketch for ideas.

Must have: 

- load maps
- draw/move walls and doors (using the line endpoints)

**Comment by Larbonard** [comment]
![EditorV1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c108ad031c9f00120c294d/125516c66e82c728ace21e0d46cd9093378d919fdeabf301b44fff9e2c4533317346f67273d5e67abc117f550d5849ad41585c45f9fedb79a5b22e6c981e5ab38532022d8c6853beb2901eb70bbb258b4a8db5be884bc3ec3825f5c6.png)

**Comment by ByteCommander** [comment]
Prototype done.

Next step is to refactor the prototype in an OOP way and extend its capabilities with more tools and better design. New issues will be opened.
